language: android

jdk:
  - oraclejdk7
  
secure: "B4mRQoqoy2ilA10NsNf76Esw05iAyrvX74uNxk7L/S7OZVSTTMsxF8dlsKYfztj4tXPiUKjBEQtdY2fnpsU6mQLLzXE45Wpn+WAIteSFvXNW6pbpZsEDrC2iCXbf5gU1YBxqOKtxNuydA1RJ8sy5Jv4wCcRp40L7aRv+uSdP6gc="

android:
  components:
  
    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

script: sh ./ci.sh

after_success:
    - git clone https://$GH_USER:$GH_TOKEN@github.com/maxirosson/jdroid.git
    - cd jdroid
    - git config user.name '$GIT_NAME'
    - git config user.email '$GIT_EMAIL'
    - git checkout artifacts
    - cp ../jdroid-sample-android/target/*  ./artifacts/master/
    - git add -A
    - git commit -m 'Adding jdroid sample android apk'
    - git push origin HEAD:artifacts
    - cd ..

deploy:
  provider: heroku
  strategy: git
  app: 
    master: jdroid-sample-server-staging
    production: jdroid-sample-server-production
  api_key:
    secure: Q8uusS6U/LmuOkCQN/j88g0OpV/E5os0ZSo2XdhD0U6Lij554F9aem54hjoxVgLilJhSv6GkD6hoBmNR1vwc2Azfh+mftBRd/x2FiikRSTf6p9l4p5c3/kvNX/c0fy6+Dcfe9NXogIFY3dhCCVTbQCTD05IZ9my4eAp629jWyFw=
