language: android

jdk:
  - oraclejdk7

env:
  global:
   # GH_USER GH_TOKEN GIT_NAME GIT_EMAIL
   - secure: "JzIWrSPF0idQ6ga0jLXnkTVQCjWML+uoEKa/IZKfJ9GvDL7KTnurhm2xRb6GIzUyrnyLAB25ag4XgPiUVDUyodbL2GXp/OxuAcDRHMOYiouH6HxxLbvoUBsqzSpRZN1miylhZWofzdZe/tPR4Avu2Dat8MQwqoRR+ceHFQqFaq4="
   # OSSRH_SERVER_USERNAME
   - secure: "LIclg2T0H3fT1OtzT9tUPvN2G9it5R+rY90EZIeVcfTVcGdjJ4toeBTAistkAl3b0vmsTVpl9e+pgR8kub7tXaaX2foWpmE5N+3K0d46PRzAyJgiF2UPGJob/OP91PFg0ckeRPVLOWNsCbrHJtTlYO9DIOBUZjfpwhEQdfhs/Yk="
   # OSSRH_SERVER_PASSWORD
   - secure: "QDzrGn4biaNM756EIXEWBKDNf7tZ3aoxNsuktU5qLOSc8KMfuCUAFrEv/HHW1MjX76/P11f6v2PlDL6VWCMjA9tqo890aVwfwuHEimkvT1qYSdw8UcNwhmYA6lPFn1ZwBPzvduby4S3YOZs2OJ4804BRgLBQ8NaESoN8S7vCcow="
   # GPG_PASSPHRASE
   - secure: "Pl/uM6KsbZbi4eBYEGcBtBV/INHSyrRZbS+P4sjqGhRzFephvSDIRLSqnjcpEfC6vs0wK3ckDgEnwo9roQ3xGzyGzq8MTm/RSIAWtaeNa8jt+SHDo97ievK6xnJdYG9VM2xZZXouENGccWsRQ+1N3eYuvhcUJIw8M6tcrHKpKt4="
   # GOOGLE_SERVER_API_KEY
   - secure: "eO8VzfFjeGySdLpN5Tqsovwj8SwVWtCt1hWcZrYcm7eK54a20fxTcgoU0p439EVxCftQruoy+ndZTRhLVxwqIEGP0pefz40JqxmmV8lp0FY7GKq29FrNxY4aS/1W9wJDijhX7H9F+vCHQD04/8RFvjqD89zOl0I6FvzVxchPx6A="
android:
  components:

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-19

script: sh ./etc/scripts/test.sh true

after_success:
    #- git clone https://$GH_USER:$GH_TOKEN@github.com/maxirosson/jdroid.git
    #- cd jdroid
    #- git config user.name "$GIT_NAME"
    #- git config user.email "$GIT_EMAIL"
    #- git checkout artifacts
    #- cp ../jdroid-sample-android/target/*.apk  ./master/
    #- git add *.apk
    #- git commit -m 'Adding jdroid sample android apk'
    #- git push origin HEAD:artifacts &> /dev/null
    #- cd ..

deploy:
  provider: heroku
  strategy: git
  app:
    master: jdroid-sample-server-staging
    production: jdroid-sample-server-production
  api_key:
    secure: Q8uusS6U/LmuOkCQN/j88g0OpV/E5os0ZSo2XdhD0U6Lij554F9aem54hjoxVgLilJhSv6GkD6hoBmNR1vwc2Azfh+mftBRd/x2FiikRSTf6p9l4p5c3/kvNX/c0fy6+Dcfe9NXogIFY3dhCCVTbQCTD05IZ9my4eAp629jWyFw=
