language: android

jdk:
  - oraclejdk7

android:
  components:

    # The BuildTools version used by your project
    - build-tools-23.0.0-rc2

    # The SDK version used to compile your project
    - android-22

script: sh ./etc/scripts/test.sh true
