language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
    - android list sdk --no-ui --all --extended

script: sh ./etc/scripts/test.sh true false true true false
